  var imgCount = 5;
        var dir = 'images/bg/';
        var randomCount = Math.round(Math.random() * (imgCount - 1)) + 1;
        var images = new Array
                images[1] = "bg_1.webp",
                images[2] = "bg_2.webp",
                images[3] = "bg_3.webp",
                images[4] = "bg_4.webp",
                images[5] = "bg_5.webp",
        document.getElementById("home").style.backgroundImage = "url(" + dir + images[randomCount] + ")"; 